# Generated by Django 4.1.2 on 2022-12-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_person_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='username',
        ),
    ]
